# 공통
spring:
  thymeleaf:
    cache: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update        # ✅ 이 줄 추가: 테이블 자동 생성/수정
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul   # ✅ Hibernate가 DB ↔ Java 변환할 때 KST 사용

  jackson:
    time-zone: Asia/Seoul   # ✅ JSON 직렬화/역직렬화도 KST로 맞춤

server:
  port: ${PORT:8080}

logging:
  level:
    org.thymeleaf: DEBUG

---
spring:
  profiles:
    active: local   # 기본 실행은 로컬
